### ISSUE TITLE
Allow copying of arbitrary non-hidden files in workdir

### ISSUE THREAD

**Issue by DreamingRaven** [JamieMagee/aur-packages-template#24]
A problem I encountered was that some of my PKGBUILDs had additional files that are packages with them. E.G https://aur.archlinux.org/packages/kubeadm-bin requires 10-kubeadm.conf. So what I did was I inserted it into the directory with the PKGBUILD and .SRCINFO then I changed this line https://github.com/DreamingRaven/aur-packages/blob/94bd5e35f2f1a9c0cdae9b51adfee12d08a05e68/.github/actions/aur/entrypoint.sh#L17 so it could be there when the package is tested.

Now I can include arbitrary files. Or at-least appears to work. Just wanted to give you a heads up, also thanks for this template repo, I am glad to see the rear end of some of these package version updates that were really dragging.

**Comment by JamieMagee** [comment]
Thanks for the info, and I'm glad to hear the template is useful. I'll update it with the changes you suggested.

**Comment by JamieMagee** [comment]
Closed in https://github.com/JamieMagee/aur-packages-template/commit/da57e99b31f4e2b726718007603e4334f44c66ae
